=== chesteric31/jsams/trunk/JSAMS/reports/estimate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="estimate">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="society" />
				<xs:element ref="customer" />
				<xs:element ref="creation_date" />
				<xs:element ref="number" />
				<xs:element ref="details" />
				<xs:element ref="total_et" />
				<xs:element ref="vat" />
				<xs:element ref="total_ati" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="society">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="vat_number" />
				<xs:element ref="address" />
				<xs:element ref="contact_info" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vat_number" type="xs:string" />
	<xs:element name="contact_info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" />
				<xs:element ref="fax" />
				<xs:element ref="mobile" />
				<xs:element ref="email" />
				<xs:element ref="website" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="phone" />
	<xs:element name="fax" />
	<xs:element name="mobile" />
	<xs:element name="email" />
	<xs:element name="website" />
	<xs:element name="customer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="first_name" />
				<xs:element ref="address" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="first_name" type="xs:string" />
	<xs:element name="creation_date" type="xs:date" />
	<xs:element name="details">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="detail" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="product" />
				<xs:element ref="quantity" />
				<xs:element ref="price" />
				<xs:element ref="total_et" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="product">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="number" />
				<xs:element ref="name" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quantity" type="xs:short" />
	<xs:element name="price" type="xs:double" />
	<xs:element name="vat" type="xs:double" />
	<xs:element name="total_ati" type="xs:double" />
	<xs:element name="name" type="xs:string" />
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="number" />
				<xs:element ref="street" />
				<xs:element ref="zip" />
				<xs:element ref="city" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="street" type="xs:string" />
	<xs:element name="zip" />
	<xs:element name="city" type="xs:string" />
	<xs:element name="number" type="xs:int" />
	<xs:element name="total_et" type="xs:double" />
</xs:schema>

=== chesteric31/jsams/JSAMS/reports/estimate.xml
<?xml version="1.0" encoding="UTF-8"?>
<estimate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="estimate.xsd">
	<society>
		<name></name>
		<vat_number></vat_number>
		<address>
			<number></number>
			<street></street>
			<zip></zip>
			<city></city>
		</address>
		<contact_info>
			<phone></phone>
			<fax></fax>
			<mobile></mobile>
			<email></email>
			<website></website>
		</contact_info>
	</society>
	<customer>
		<name></name>
		<first_name></first_name>
		<address>
			<number></number>
			<street></street>
			<zip></zip>
			<city></city>
		</address>
	</customer>
	<creation_date></creation_date>
	<number></number>
	<details>
		<detail>
			<product>
				<number></number>
				<name></name>
			</product>
			<quantity></quantity>
			<price></price>
			<total_et></total_et>
		</detail>
	</details>
	<total_et></total_et>
	<vat></vat>
	<total_ati></total_ati>
</estimate>
